// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: backtest.proto

package backtest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunBacktestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *RunBacktestReq) Reset() {
	*x = RunBacktestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backtest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunBacktestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunBacktestReq) ProtoMessage() {}

func (x *RunBacktestReq) ProtoReflect() protoreflect.Message {
	mi := &file_backtest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBacktestReq.ProtoReflect.Descriptor instead.
func (*RunBacktestReq) Descriptor() ([]byte, []int) {
	return file_backtest_proto_rawDescGZIP(), []int{0}
}

func (x *RunBacktestReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RunBacktestRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Result bool   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *RunBacktestRes) Reset() {
	*x = RunBacktestRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backtest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunBacktestRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunBacktestRes) ProtoMessage() {}

func (x *RunBacktestRes) ProtoReflect() protoreflect.Message {
	mi := &file_backtest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBacktestRes.ProtoReflect.Descriptor instead.
func (*RunBacktestRes) Descriptor() ([]byte, []int) {
	return file_backtest_proto_rawDescGZIP(), []int{1}
}

func (x *RunBacktestRes) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RunBacktestRes) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_backtest_proto protoreflect.FileDescriptor

var file_backtest_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x61, 0x63, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x0e, 0x52, 0x75,
	0x6e, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x3c, 0x0a, 0x0e, 0x52, 0x75, 0x6e, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x9a,
	0x01, 0x0a, 0x08, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x0b, 0x52,
	0x75, 0x6e, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x62, 0x61, 0x63,
	0x6b, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x75, 0x6e, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x52, 0x75, 0x6e, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x4b,
	0x0a, 0x11, 0x52, 0x75, 0x6e, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x18, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x52,
	0x75, 0x6e, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x62, 0x61, 0x63, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x75, 0x6e, 0x42, 0x61, 0x63, 0x6b,
	0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x61,
	0x70, 0x69, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_backtest_proto_rawDescOnce sync.Once
	file_backtest_proto_rawDescData = file_backtest_proto_rawDesc
)

func file_backtest_proto_rawDescGZIP() []byte {
	file_backtest_proto_rawDescOnce.Do(func() {
		file_backtest_proto_rawDescData = protoimpl.X.CompressGZIP(file_backtest_proto_rawDescData)
	})
	return file_backtest_proto_rawDescData
}

var file_backtest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_backtest_proto_goTypes = []interface{}{
	(*RunBacktestReq)(nil), // 0: backtest.RunBacktestReq
	(*RunBacktestRes)(nil), // 1: backtest.RunBacktestRes
}
var file_backtest_proto_depIdxs = []int32{
	0, // 0: backtest.Backtest.RunBacktest:input_type -> backtest.RunBacktestReq
	0, // 1: backtest.Backtest.RunBacktestStream:input_type -> backtest.RunBacktestReq
	1, // 2: backtest.Backtest.RunBacktest:output_type -> backtest.RunBacktestRes
	1, // 3: backtest.Backtest.RunBacktestStream:output_type -> backtest.RunBacktestRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backtest_proto_init() }
func file_backtest_proto_init() {
	if File_backtest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backtest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunBacktestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backtest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunBacktestRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backtest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backtest_proto_goTypes,
		DependencyIndexes: file_backtest_proto_depIdxs,
		MessageInfos:      file_backtest_proto_msgTypes,
	}.Build()
	File_backtest_proto = out.File
	file_backtest_proto_rawDesc = nil
	file_backtest_proto_goTypes = nil
	file_backtest_proto_depIdxs = nil
}
