# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backtest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='backtest.proto',
  package='backtest',
  syntax='proto3',
  serialized_options=b'Z\014api/backtest',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x62\x61\x63ktest.proto\x12\x08\x62\x61\x63ktest\"\x1e\n\x0eRunBacktestReq\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\".\n\x0eRunBacktestRes\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x08\x32\x9a\x01\n\x08\x42\x61\x63ktest\x12\x41\n\x0bRunBacktest\x12\x18.backtest.RunBacktestReq\x1a\x18.backtest.RunBacktestRes\x12K\n\x11RunBacktestStream\x12\x18.backtest.RunBacktestReq\x1a\x18.backtest.RunBacktestRes(\x01\x30\x01\x42\x0eZ\x0c\x61pi/backtestb\x06proto3'
)




_RUNBACKTESTREQ = _descriptor.Descriptor(
  name='RunBacktestReq',
  full_name='backtest.RunBacktestReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='backtest.RunBacktestReq.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=58,
)


_RUNBACKTESTRES = _descriptor.Descriptor(
  name='RunBacktestRes',
  full_name='backtest.RunBacktestRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='backtest.RunBacktestRes.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='backtest.RunBacktestRes.result', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['RunBacktestReq'] = _RUNBACKTESTREQ
DESCRIPTOR.message_types_by_name['RunBacktestRes'] = _RUNBACKTESTRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunBacktestReq = _reflection.GeneratedProtocolMessageType('RunBacktestReq', (_message.Message,), {
  'DESCRIPTOR' : _RUNBACKTESTREQ,
  '__module__' : 'backtest_pb2'
  # @@protoc_insertion_point(class_scope:backtest.RunBacktestReq)
  })
_sym_db.RegisterMessage(RunBacktestReq)

RunBacktestRes = _reflection.GeneratedProtocolMessageType('RunBacktestRes', (_message.Message,), {
  'DESCRIPTOR' : _RUNBACKTESTRES,
  '__module__' : 'backtest_pb2'
  # @@protoc_insertion_point(class_scope:backtest.RunBacktestRes)
  })
_sym_db.RegisterMessage(RunBacktestRes)


DESCRIPTOR._options = None

_BACKTEST = _descriptor.ServiceDescriptor(
  name='Backtest',
  full_name='backtest.Backtest',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=109,
  serialized_end=263,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunBacktest',
    full_name='backtest.Backtest.RunBacktest',
    index=0,
    containing_service=None,
    input_type=_RUNBACKTESTREQ,
    output_type=_RUNBACKTESTRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RunBacktestStream',
    full_name='backtest.Backtest.RunBacktestStream',
    index=1,
    containing_service=None,
    input_type=_RUNBACKTESTREQ,
    output_type=_RUNBACKTESTRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BACKTEST)

DESCRIPTOR.services_by_name['Backtest'] = _BACKTEST

# @@protoc_insertion_point(module_scope)
