# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import backtest_pb2 as backtest__pb2


class BacktestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunBacktest = channel.unary_unary(
                '/backtest.Backtest/RunBacktest',
                request_serializer=backtest__pb2.RunBacktestReq.SerializeToString,
                response_deserializer=backtest__pb2.RunBacktestRes.FromString,
                )
        self.RunBacktestStream = channel.stream_stream(
                '/backtest.Backtest/RunBacktestStream',
                request_serializer=backtest__pb2.RunBacktestReq.SerializeToString,
                response_deserializer=backtest__pb2.RunBacktestRes.FromString,
                )


class BacktestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunBacktestStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BacktestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.RunBacktest,
                    request_deserializer=backtest__pb2.RunBacktestReq.FromString,
                    response_serializer=backtest__pb2.RunBacktestRes.SerializeToString,
            ),
            'RunBacktestStream': grpc.stream_stream_rpc_method_handler(
                    servicer.RunBacktestStream,
                    request_deserializer=backtest__pb2.RunBacktestReq.FromString,
                    response_serializer=backtest__pb2.RunBacktestRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'backtest.Backtest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Backtest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/backtest.Backtest/RunBacktest',
            backtest__pb2.RunBacktestReq.SerializeToString,
            backtest__pb2.RunBacktestRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunBacktestStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/backtest.Backtest/RunBacktestStream',
            backtest__pb2.RunBacktestReq.SerializeToString,
            backtest__pb2.RunBacktestRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
